refactored module01
swarmauri/swarmauri-notebooks pull request #216
Opened 2024-12-17 14:41 UTC by 3rd-Son

This PR contains a refactored version of module01
Removed unnecessary information and added important ones

2024-12-17 16:27 UTC, cobycloud requested changes
small changes, but overall a good refresh

2024-12-17 16:27 UTC, cobycloud commented on courses/GENAI/Module_01_Introduction_to_Swarmauri/Notebook_02_SDK_Installation_Setup.ipynb
please also show how to add the env as a juypter kernel

2024-12-17 16:27 UTC, cobycloud commented on courses/GENAI/Module_01_Introduction_to_Swarmauri/Notebook_03_Features_of_Swarmauri.ipynb
explain the general pattern, for example:

"to import you can use `from swarmauri.<resource_kind>.concrete import <subclass type>`

something along those lines, so they understand generally how to navigate. Explain that we provide many subtypes and that the few shown here are just examples

2024-12-18 07:04 UTC, 3rd-Son commented on courses/GENAI/Module_01_Introduction_to_Swarmauri/Notebook_03_Features_of_Swarmauri.ipynb
On it

2024-12-18 07:54 UTC, 3rd-Son commented
@cobycloud 
All changes have been made

2024-12-19 05:21 UTC, cobycloud approved these changes

2024-12-19 05:21 UTC, merged